### PR TITLE
Add ability to delete entire groups / categories

### PR DESCRIPTION
**Pull request by michealt17**
Not sure if you are open to PR's but I added a quick way to delete entries by group as that's generally what I do mostly. Far from perfect but handy to have.

### CODE REVIEW

**Comment by mikhoul** [comment]
@michealt17 Hi, 

I see that you have forked Eddy and I'd really like to use the latest version but there is no executable/binary available, would you mind to build one on your fork and make it available for users ? 🤔

Regards :octocat:

**Comment by michealt17** [comment]
> @michealt17 Hi,
> 
> I see that you have forked Eddy and I'd really like to use the latest version but there is no executable/binary available, would you mind to build one on your fork and make it available for users ? 🤔
> 
> Regards :octocat:

Sure no problem. Far from perfect but does the job. Have zipped a release build.

**Comment by mikhoul** [comment]
Could you activate the "Issues" on your fork since when I try to open an M3U it throw an exception error and sending you the log of the error opening an issue on your fork will be better suited. :wink:

**Comment by michealt17** [comment]
Sorry I didn't have time to test it to be honest. I'll open the issues
later and have a look at this.

**Comment by michealt17** [comment]
Issues open

**Comment by Gabrieldenys** [comment]
Hey all, I merged the PR. Sorry for not being active on this project, I forgot about this account and it's been years.

**Comment by michealt17** [comment]
> Hey all, I merged the PR. Sorry for not being active on this project, I forgot about this account and it's been years.

Thanks, handy tool. Couldn't find anything that allowed deleting whole groups so this is probably the bare minimum to achieve that.

**Pull request merged**
